### ISSUE TITLE
Lex Rebuild throwing error

### ISSUE THREAD

**Issue by xtrip15** [aws-solutions/qnabot-on-aws#144]
Using latest version of qna builder.

Looks like it tries to send few requests before request comes back with failure.

GET https://xxxxxx.execute-api.us-east-1.amazonaws.com/prod/bot

{
    "lambdaArn": "arn:aws:lambda:us-east-1:382758891647:function:QNA-dev-dev-master-1-FulfillmentLambda-XXXXXX",
    "lambdaRole":"QNA-dev-dev-master-1-FulfillmentLambdaRole-XXXXX",
    "status":"READY",
    "build":{"status":"Failed","token":"XXXXX+tiqL1Xh9FnsQ=="},
    "botname":"QNA_dev_dev_master_one_Botnt",
    "botversion":"BotAliasxbKluJE",
    "messages":{
        "clarification":[
                        "Sorry, I did not understand your question"                    ],
        "abort":[
                        "Sorry, I did not understand question"                    ]
    },
    "_links":{
        "alexa":{
            "href":"https://xxxxxx.execute-api.us-east-1.amazonaws.com/prod/bot/alexa"
        }
    }
}

**Comment by xtrip15** [comment]
It appears to me that there is size limit and it fails after certain number/size. Perhaps 400+ questions? Then it fails at Rebuilding Slot (1st step) only and doesnt proceed to subsequent steps.

**Comment by markseddon** [comment]
I had the same problem. My issue was due to importing questions with a length greater than 140 characters. I found the following error in the CloudWatch Logs for the Lambda.

`The value specified for 'enumerationValues.309.member.value' is invalid. Member must have length less than or equal to 140`

The questions are inserted as [EnumerationValues](https://docs.aws.amazon.com/lex/latest/dg/API_EnumerationValue.html) when the LexBuild Lambda creating / updating the [SlotType](https://docs.aws.amazon.com/lex/latest/dg/API_PutSlotType.html). EnumerationValues have a max length of 140 characters. This is clear in the UI but not obvious in importing. 

I'll look into adding some validation for question length in the import script.
