### ISSUE TITLE
QnA in Spanish?

### ISSUE THREAD

**Issue by papagala** [aws-solutions/qnabot-on-aws#226]
Hey Guys, 

Great job with this repo/cloud formation stack, it's awesome. This is not an issue but I wonder if you guys were thinking of supporting the newly released Spanish Language into Lex. 

Feel free to close it anytime and thank you!

**Comment by rstrahan** [comment]
Thanks Oswaldo, Glad you like our bot. Yes, we are definitely thinking about it! No firm plans yet, but for sure we'd like to do it.. It will be especially useful in call center applications since it will allow us to support spanish language voice interaction.

Sent from Workspace ONE Boxer

On Oct 1, 2020 6:42 PM, Oswaldo Gomez <notifications@github.com> wrote:

Hey Guys,

Great job with this repo/cloud formation stack, it's awesome. This is not an issue but I wonder if you guys were thinking of supporting the newly released Spanish Language into Lex.

Feel free to close it anytime and thank you!

-
