### ISSUE TITLE
Thoughts on "Exit", "Start Over", and "Back" type options?

### ISSUE THREAD

**Issue by dfetterman** [aws-solutions/qnabot-on-aws#277]
We're using QNABot to help users troubleshoot certain issues and if it's not successful, gather information from the user and create a Remedy ticket. We're using Elicit Response bots to get user input and document chaining rules with JavaScript conditional expressions to present the next card in a decision tree.

Some users are getting stuck in a decision tree and I'd like to have an options for allowing them to exit the decision tree entirely, start at the root of the decision tree, or just go back a card. When using the QNAFreeText bot w/ elicit response, I can use the JavaScript conditional expressions to do this but that's not going to work when using other response bots such as QNAPhoneNumber because they validate the input before it has a chance to become a SessionAttributes.

I just wanted to get some thoughts on the best way to work around this.

Thanks,
Dane

**Comment by rstrahan** [comment]
Hi @dane, You could maybe create elicit response bots that include an additional 'exit' intent (with an 'exit' slot). Then if users reply to the question, or to a confirmation prompt, with the exit intent utterance, the exit slot will be filled and you could check for  it in the conditional chaining expression.
If you try that please let us know how it goes. If you are successful please send us a PR and we we could maybe make that a standard feature of the response bots going forward.
Cheers
Bob

Sent from Workspace ONE Boxer

On Jun 23, 2021 12:48 PM, Dane ***@***.***> wrote:

We're using QNABot to help users troubleshoot certain issues and if it's not successful, gather information from the user and create a Remedy ticket. We're using Elicit Response bots to get user input and document chaining rules with JavaScript conditional expressions to present the next card in a decision tree.

Some users are getting stuck in a decision tree and I'd like to have an options for allowing them to exit the decision tree entirely, start at the root of the decision tree, or just go back a card. When using the QNAFreeText bot w/ elicit response, I can use the JavaScript conditional expressions to do this but that's not going to work when using other response bots such as QNAPhoneNumber because they validate the input before it has a chance to become a SessionAttributes.

I just wanted to get some thoughts on the best way to work around this.

Thanks,
Dane

-

**Comment by bobpskier** [comment]
Piggybacking on Bob S's reply, I believe you could also turn off confirmation prompting in this new elicit response bot. User enters phone number or 'exit' or 'agent' or 'help' or some other string in the separate slot which is detected and used in conditional chaining rule. The QNAYesNoExit does something similar but its not exactly the same as what would be done. In this new bot, the phonenumber and exit/agent/menu slot would both need to be optional.
