### ISSUE TITLE
Hook to render response from Kendra

### ISSUE THREAD

**Issue by garretunderhill** [aws-solutions/qnabot-on-aws#472]
**Is your feature request related to a problem? Please describe.**
The data returned from Kendra is in raw text

**Describe the feature you'd like**
Using a Lambda function, intercept the Kendra response and change to markdown

**Comment by ihmaws** [comment]
Hi @garretunderhill , sorry for not getting to this in a timely manner.

Unfortunately, it isn't clear to me what the request in this issue is. If you are still experiencing challenges with this, please create a new issue stating the version you are on, the problem you have, and what you'd like to see.

A simple example to help reproduce will go a long way! To the best of my understanding, if you are using the aws-lex-web-ui front-end, Kendra responses are returned in a markdown format with the keywords highlighted and source links appropriately hyperlinked.
