### ISSUE TITLE
Mechanism to force a custom intent. 

### ISSUE THREAD

**Issue by GGONCONCENTRIX** [aws-solutions/qnabot-on-aws#480]
The customer is looking for a mechanism to force a custom intent. By default, Lex uses the fallback intent, where the customer is looking for a specific custom intent. To get around this, a Lambda function was hooked to handle this and force the fallback intent. The issue now is that Lex isn’t returning a ‘retries’ value to lambda as a session attribute. This means that it isn’t possible to terminate the interaction after ‘x’ number of invalid entries. AWS recommendations:

 - Use parameter store so the Lambda can check a counter stored there, and take action based on that as a workaround (i.e., go to fallback intent).
 - Pass session attributes to Lambda hook to allow decrementing the counter (enforce 'x' number of retries).

Request:
Include a mechanism for solution to force a custom intent, with appropriate error handling.

**Comment by ihmaws** [comment]
Hi @GGONCONCENTRIX, sorry for the delay in getting around to this.

Unfortunately, it isn't clear to me what the request in this issue is. If you or your customer are still experiencing challenges with this, please create a new issue stating the version you are on, the problem you have, and what you'd like to see.

A simple example to help reproduce will go a long way!
