### ISSUE TITLE
Cant get ClientFiltering to work

### ISSUE THREAD

**Issue by kmaramr** [aws-solutions/qnabot-on-aws#518]
**Describe the bug**
We are trying to use ClientFiltering to segregate questions into department scopes. None of the questions seem to work (we have set the ClientFilterValue for all the questions). Once we remove it we get a hit. Cloud watch logs show no_hits when its set.

**To Reproduce**
- Set the "clientFilterValues" on the questions being deployed. 
- Set the lex sessions attribute "QNAClientFilter" on the test page. 

**Expected behavior**
Expect to see the response from the es query. And not the no_hit match.

**Please complete the following information about the solution:**
- QnaBot version: 5.2.1
- Lex web ui version: 0.19.6

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0189) QnABot [...] **v0.0.1**_".

- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [x] Were there any errors in the CloudWatch Logs?
[log-events-viewer-result.csv](https://github.com/aws-solutions/qnabot-on-aws/files/10015276/log-events-viewer-result.csv)

**Comment by t-jones** [comment]
Looks like the issue in this case is due to using the `term` operator for `clientFilterValue`, which only does an exact match.  The `clientFilterValue` used was capitalized.  The field is a text field and subject to the analyzer, so it was transparently being lowercased, which caused the match to fail.

https://github.com/aws-solutions/qnabot-on-aws/blob/main/lambda/es-proxy-layer/lib/esbodybuilder.js#L82

https://opensearch.org/docs/latest/opensearch/query-dsl/term/#term
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html

cc: @chrislott

**Comment by ihmaws** [comment]
Thank you @kmaramr for the report and @t-jones for the fix.

Fixed as of v5.2.5
