### ISSUE TITLE
Password reset function not working 

### ISSUE THREAD

**Issue by reimannlars** [aws-solutions/qnabot-on-aws#612]
**Describe the bug**
The password reset function is not working as expected. After the initial admin user creation and the forced password change, the email address associated with that user is still unconfirmed. 
No confirmation email was received/sent. 
With unconfirmed email addresses, the password reset function does not seem to work and throws an error "Could not reset password for the account, please contact support or try again".

**To Reproduce**
deploy the solution and try to use "password forgotten link"

**Expected behavior**
After initial deployment a verification email is sent out to confirm users address. 
Password reset function is tested and works.

**Please complete the following information about the solution:**
- (SO0189) QnABot with admin and client websites - (Version v5.3.4)

- [ ] Region: [e.g. eu-central-1]
- [ no ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ yes ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by marcburnie** [comment]
Thanks for raising this issue. I've been able to reproduce this. I'll get back to you once we have a fix scheduled for release.

**Comment by marcburnie** [comment]
Hi @reimannlars, unfortunately the fix to resolve this issue will create a breaking change for existing users to upgrade, since we'd need to modify the existing user attributes with Cloudformation. We will not resolve this issue because the inconvenience of forcing our users to migrate their Cognito user pool is much greater than working around this issue. There is a relatively simple workaround using the AWS CLI which we currently recommend and will also document in the next release:

1. Install the AWS CLI
2. Execute the following command:
```
aws cognito-idp admin-set-user-password \
  --user-pool-id <qnabot user pool id> \
  --username <default username> \
  --password <desired password> \
  --permanent
```
You can get the user pool id using:
```
aws cognito-idp list-user-pools --max-results 10
```

Alternatively, you can delete and create a user with the same name from the Cognito console. The user needs to be added to the 'Admins' user group:

1. From the Cognito console, disable and delete the default user.
2. Create a new user with the same name or different name. You can provide a new password or generate a new sign-in e-mail.
3. Once created, under the 'Groups' tab, click on the 'Admins' group and add the user to that group.
