### ISSUE TITLE
Responses marked by the user with Thumbs up/down are reported in both Kibana widgets: Positive/negative feedback

### ISSUE THREAD

**Issue by cristi-constantin** [aws-solutions/qnabot-on-aws#659]
I have my Thumbs up/down utterances marked to create Lex intents. I then played with four questions from the questions bank and marked two answers with thumbs up and the other two - with thumbs down. When I check the Kibana dashboard and click on 'Inspect' of both 'Positive feedback' and 'Negative feedback', I see all of my four questions in the sliding window. I expected to see just two of them on the 'Inspect' of 'Positive feedback' and the other two on the 'Negative feedback.'

Am I doing it wrong, or is it a bug?

**Comment by marcburnie** [comment]
Hi @cristi-constantin, there is a typo in the Kibana dashboard. The syntax is incorrect in the DQL query
`feedback=correct` should be `feedback:correct`. You can edit this yourself from the Kibana dashboard by clicking 'Edit' on the top right and clicking the gear icon and 'Edit Visualization' in both positive and negative visualizations. Replace both `=` with `:`. See example screenshot below:

![image](https://github.com/aws-solutions/qnabot-on-aws/assets/63939269/e90aa44b-7372-4adf-a426-3c7a52c10ced)

We'll have this fixed in the next minor release.

**Comment by cristi-constantin** [comment]
Confirmed as fixed, If I change that manually.
