### ISSUE TITLE
Unable to add question when deployed via custom deployment

### ISSUE THREAD

**Issue by abilash44** [aws-solutions/qnabot-on-aws#663]
**Describe the bug**
I followed the instructions to setup the QnA bot via the custom deployment instruction. After logging in to the content designer and I add a question and hit refresh, the question disappears. 

**To Reproduce**
1. Follow the custom setup guide.
2. Login as Admin to the content designer
3. Add a question, any type
4. Give a question and an answer (any text will do)
5. Hit save 
6. give it a few seconds
7. Hit refresh, the entered questions all disappear.

**Expected behavior**
Expected behavior is for the questions to be saved and the client bot reply to these questions. 

**Please complete the following information about the solution:**
current latest version available from git

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0189) QnABot [...] **v0.0.1**_".

- [Y] Region: [e.g. us-east-1]
- [N] Was the solution modified from the version published on this repository?
- [-] If the answer to the previous question was yes, are the changes available on GitHub?
- [N] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? 
-- Do not see any error when deploying via CF
- [-] Were there any errors in the CloudWatch Logs?
-- Not sure how to find these logs 
**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/7634986/462957ee-6022-4e43-9ce5-d269652b2643)

**Comment by marcburnie** [comment]
Hi @abilash44 - the cause of this problem is likely due to a mismatch in the Embeddings settings or a problem with the OpenSearch cluster.

Can you please try:
1. From content designer go to 'Settings'
2. Check the 'EMBEDDINGS_ENABLE' setting. If it is set to true then set it to 'false' and try creating a question again. If it's already false then the cause of your issue is likely due to OpenSearch.

If the above didn't fix your issue, then please attach the following information:
1. A screenshot of your CloudFormation parameters.
2. CloudWatch logs from the ESProxyLambda: https://us-east-1.console.aws.amazon.com/lambda/home?region=us-east-1#/functions?fo=and&o0=%3A&v0=esproxy. Select 'Monitor' -> 'View Cloudwatch Logs' -> 'Search Log Groups' -> 'Actions' -> 'Download Search Results (CSV)'
3. Cluster Health of OpenSearch cluster and Indexes: https://us-east-1.console.aws.amazon.com/aos/home?region=us-east-1#opensearch/dashboard

**Comment by abilash44** [comment]
Chaning it to FALSE seems to work. What does EMBEDDINGS_ENABLE do and do I need to have it on?
Also more clearer error prompts would have been a lot helpful

**Comment by marcburnie** [comment]
You can read more about embeddings and semantic matching here: https://github.com/aws-solutions/qnabot-on-aws/tree/main/docs/semantic_matching_using_LLM_embeddings. In short, the capability adds semantic matching vs the standard keyword matching, so a question like "Where does the president live?" and "What is the White House address?" match against the same question.

The embeddings vector is generated from a machine learning model that is deployed when the Cloudformation `EmbeddingsAPI` parameter is set to `SAGEMAKER`. If `EMBEDDINGS_ENABLE` is set to `true` and there is no Embeddings model deployed, then any request to the create question endpoint will fail, since the embeddings vector should be created at this time. I assume this is the cause of your problem.

If you want the semantic matching capability then you can get this working again by setting `EMBEDDINGS_ENABLE` to `true` in your content designer settings and set the Cloudformation parameter `EmbeddingsAPI` to `SAGEMAKER`. Otherwise, you need to turn the feature off by setting `EMBEDDINGS_ENABLE` to `false` as you have already done.

Besides this, I think your expectation of clearer error prompts is valid. If you don't mind creating a separate feature request for this (https://github.com/aws-solutions/qnabot-on-aws/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.md&title=) then we can address that issue separately.

**Comment by abilash44** [comment]
That makes sense. How do I ensure that this flag is set to false when doing the custom deployment?

**Comment by marcburnie** [comment]
The default settings from GitHub have `EmbeddingsAPI` set to `SAGEMAKER`, so this feature should have been enabled by default. You can turn this feature off when deploying using the command line by modifying the config.json in your root directory, which is generated when you run the `npm run config` command. Here is an example config.json with the `EmbeddingsAPI` set to `DISABLED`:

```JSON
{
  "region": "us-east-1",
  "profile": "default",
  "publicBucket": "aws-bigdata-blog",
  "publicPrefix": "artifacts/aws-ai-qna-bot",
  "devEmail": "user@example.com",
  "devEncryption": "ENCRYPTED",
  "devPublicOrPrivate": "PRIVATE",
  "namespace": "dev",
  "LexBotVersion": "LexV2 Only",
  "LexV2BotLocaleIds": "en_US,es_US,fr_CA",
  "stackNamePrefix": "QNA",
  "skipCheckTemplate": false,
  "noStackOutput": false,
  "multiBucketDeployment": false,
  "buildType": "Custom",
  "FulfillmentConcurrency": 1,
  "EmbeddingsApi": "DISABLED",
  "QASummarizeApi": "SAGEMAKER",
  "InstallLexResponseBots": true
}
```
