### ISSUE TITLE
KendraFallback missing in import 

### ISSUE THREAD

**Issue by abilash44** [aws-solutions/qnabot-on-aws#667]
**Describe the bug**
KendraFallback extension is missing in import section

**To Reproduce**
Follow the steps in https://github.com/aws-solutions/qnabot-on-aws/tree/main/docs/kendra_fallback

**Expected behavior**
Should find an extension named "KendraFallback"

**Please complete the following information about the solution:**
latest CF template from https://docs.aws.amazon.com/solutions/latest/qnabot-on-aws/step-1-launch-the-stack.html

**Screenshots**
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/7634986/9ff80ba6-ff32-4bb1-aa3f-125dd4df6610)
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/7634986/e93897b4-e934-4b7b-a05d-33020e01c880)

**Additional context**
This might be a simple over look. If there is some other changes, please update the doc as needed.

**Comment by marcburnie** [comment]
Hi @abilash44 - this is old documentation which will be updated during the next release. The KendraFallback example is actually part of the default behavior of QnABot now. I recommend following the following steps in our Implementation Guide if you're interested in integrating Kendra: https://docs.aws.amazon.com/solutions/latest/qnabot-on-aws/integrate-amazon-kendra.html. I will leave this ticket open until we make corrections to the documentation.

**Comment by abilash44** [comment]
That is awesome. Is there a way we can control the default behavior. Like I want to ask if the kendra results are useful, if not either let the user ask for more kendra results or choose to do next option.

**Comment by marcburnie** [comment]
That is correct - you get to define what the search query is using Kendra redirect.

Adding lambda hooks requires creating and deploying your own lambda function that can understand and respond to the QnABot fulfillment lambda request/response objects. Adding that function to respond to a users question using QnABot is relatively simple though: you just need to add the lambda name to the question (or to pre-processing/post-processing lambda hooks if you want to append the lambda before or after every question). See: https://github.com/aws-solutions/qnabot-on-aws/tree/main/docs/lambda_hooks. This allows you to extend the existing functionality of QnABot however you want/need. We include some examples to get started (see: https://github.com/aws-solutions/qnabot-on-aws/blob/main/templates/examples/examples/js/hook.js). A more relevant example can be found here: https://github.com/aws-samples/qnabot-on-aws-plugin-samples/tree/main/lambdas/qna_bot_qbusiness_lambdahook, which integrates the new AWS service 'Q' with QnA Bot instead of using Kendra as the fallback.

**Comment by marcburnie** [comment]
Closing this issue. The documentation has been updated in v5.5.0 to remove reference to non-existent import.
