### ISSUE TITLE
Using lambda_hook_sdk  in lambda (lambda hook)

### ISSUE THREAD

**Issue by dangollayan** [aws-solutions/qnabot-on-aws#685]
Trying to use hook.set_message(event, message) under lambda_hook_sdk, but it only changes the messages under event.res.result, not the event.res.message. Therefore, the changes I applied to the message using hook.set_message don't reflect on the bot.

Reference:
https://github.com/aws-solutions/qnabot-on-aws/blob/main/docs/lambda_hooks/lambda_hook_sdk.MD

Scenario:
First, I used hook.get_message(event) to retrieve the message:
{
"plainText": "Thank you, dan! 😄",
"markDown": "Thank you, dan! 😄"
}
Then, I used hook.set_message(event, message) where my message is:
{
"plainText": "Thank you, Dan! 😄",
"markDown": "Thank you, Dan! 😄"
}

However, when I tried chatting with the bot, it still responded with "Thank you, dan! 😄"

**Comment by jangidms** [comment]
Hi @dangollayan 
Thanks for reporting this. We'll look into this and get back to you

**Comment by michaelin-96** [comment]
Hey @dangollayan, can I ask how you set up your lambda hook function? You are right in that set_message changes event.res.result and not event.res.message. In order to return back event.res.result, you must override event.res.message at the end of you lambda function by putting (as an example):

`event.res.message = event.res.result.a` 
or you can also use the get_message() 
`event.res.message = hooks.get_message(event).plainText`

**Comment by dangollayan** [comment]
thanks @michaelin-96, that's what I actually did, I manually changed the value from event.res.message. I just thought that if you use the set_message, it will be the actual output message.

**Comment by michaelin-96** [comment]
I agree, that confused me at first as well. I did look into the unit tests and other example lambda hook code, and I believe that is the intended use for set_message(). 

The documentation for lambda hook sdk could use a bit of update/clarification and I plan to update it in future releases! Thanks!

**Comment by dangollayan** [comment]
Thank you @michaelin-96 !!!
