### ISSUE TITLE
Unusual behaviour of invalid slot input

### ISSUE THREAD

**Issue by dangollayan** [aws-solutions/qnabot-on-aws#696]
Describe the Issue:
We are encountering intermittent responses when inputting invalid values into a slot. Occasionally, the response originates from the ELICIT_RESPONSE_RETRY_MESSAGE,
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/113376990/efbb9f23-b2fb-4127-9a2c-958a368ee26a)
while at other times, it stems directly from the slot message within the bot.
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/113376990/da3a6504-13b9-49dc-acb4-1fc0739fd9ab)

Please refer to this sample:
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/113376990/b597be37-5eba-4ab1-945e-9ee9ffdae7a5)

Steps to Reproduce:

1. Initially, a custom responseBot was created. You can refer to this extracted bot JSON 
[QNAName_Bot-DRAFT-JYGSKBYNQI-LexJson(1).zip](https://github.com/aws-solutions/qnabot-on-aws/files/14355617/QNAName_Bot-DRAFT-JYGSKBYNQI-LexJson.1.zip)

2. The content of this responseBot solely comprises the sample utterance and a slot with the type AMAZON.FirstName.
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/113376990/e28416f4-2ad9-4e9d-9400-d8c54e7055e6)

3. Integration was established with a question from the QnA Bot Designer.
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/113376990/b4d2ec71-ea26-4ab6-810a-69d3427a06c2)

Expected behavior:
N/A

**Please complete the following information about the solution:**
- [Version v5.5.0 ] Version
- [ Sydney] Region:
- [no] Was the solution modified from the version published on this repository?
- [ x] If the answer to the previous question was yes, are the changes available on GitHub?
- [yes] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [no] Were there any errors in the CloudWatch Logs?

**Comment by dougtoppin** [comment]
@dangollayan Thank you for your report. We will investigate and get back to you.

**Comment by fhoueto-amz** [comment]
Hi @dangollayan 
This is the expected behavior. Please to https://docs.aws.amazon.com/lexv2/latest/dg/built-in-intent-fallback.html.  As stated "Amazon Lex V2 matches the fallback intent in these situations:

    The user's input to an intent doesn't match the input that the bot expects

    Audio input is noise, or text input isn't recognized as words.

    The user's input is ambiguous and Amazon Lex V2 can't determine which intent to invoke."

So when your input is not recognized as words, the main bot Fallback is invoked right away. When your input is recognized as words, the qna main bot intent is invoked which passes the input to your elicit bot which then tries to match the name and will fall back if not recognizing a name. So the intent match is what is playing out here. Even with the same input, as previous context of the conversation are passed through the intent match may vary i.e. the same intent can match a slot in a given context but not in another context.
